name: Build and Release Github

on:
  pull_request:
    branches: [automate]
    
  push:
    branches: [automate]

  workflow_dispatch:
    inputs:
      version:
        description: '1.4'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.0

      - name: Set up JDK
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Give Permission
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload Build artifacts
        uses: actions/upload-artifact@v3.1.3
        with:
          name: sample-automation.apk
          path: app/build/outputs/apk/release/app-debug.apk

      - name: Debug Output
        run: |
          ls -R app/release/
          ls -R app/build/outputs/apk/release/